# docker/Dockerfile.writer
# syntax=docker/dockerfile:1.7

FROM eclipse-temurin:21-jdk AS build
WORKDIR /src
COPY . /src/
RUN ./gradlew :writer:installDist --no-daemon

FROM eclipse-temurin:21-jre
ENV JAVA_OPTS="-XX:+UseZGC -XX:+ZGenerational"
WORKDIR /app
COPY --from=build /src/writer/build/install/writer /app/
EXPOSE 8092
ENTRYPOINT ["/app/bin/writer"]
