#!/usr/bin/env bash
# Bootstraps a CryptoLake VPS host: prompts for the secrets, writes
# .env, installs Docker, the data dir, swap, log rotation, the systemd
# unit, and the disk-monitor cron.
#
# This script does NOT do security hardening — that's harden.sh, which
# you should have run first. This script also does NOT pull or run the
# stack — that happens after you publish images from your laptop.
#
# Run as a non-root user with sudo:  sudo bash infra/vps/bootstrap.sh
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DATA_DIR_DEFAULT="/data"
SWAP_SIZE="2G"

red()    { printf '\033[0;31m[x]\033[0m %s\n' "$*" >&2; }
yellow() { printf '\033[1;33m[!]\033[0m %s\n' "$*"; }
green()  { printf '\033[0;32m[+]\033[0m %s\n' "$*"; }
section(){ echo; printf '\033[1m== %s ==\033[0m\n' "$*"; }

require_root() {
  [[ $EUID -eq 0 ]] || { red "Run with sudo: sudo bash infra/vps/bootstrap.sh"; exit 1; }
  [[ -n "${SUDO_USER:-}" && "$SUDO_USER" != "root" ]] \
    || { red "Run via sudo as a non-root user (not as root directly)."; exit 1; }
}

prompt_default() {
  # prompt_default <var> <prompt> <default>
  local _var="$1" _prompt="$2" _default="$3" _input
  read -r -p "$_prompt [$_default]: " _input </dev/tty || _input=""
  printf -v "$_var" '%s' "${_input:-$_default}"
}

prompt_secret() {
  # prompt_secret <var> <prompt>  (no echo, no default)
  local _var="$1" _prompt="$2" _input
  read -r -s -p "$_prompt: " _input </dev/tty
  echo
  printf -v "$_var" '%s' "$_input"
}

prompt_yesno() {
  # prompt_yesno <prompt> <default-yn>  → returns 0 for yes, 1 for no
  local _prompt="$1" _default="$2" _input _hint
  case "$_default" in y|Y) _hint="Y/n";; *) _hint="y/N";; esac
  read -r -p "$_prompt [$_hint]: " _input </dev/tty || _input=""
  _input="${_input:-$_default}"
  case "$_input" in y|Y|yes|YES) return 0;; *) return 1;; esac
}

collect_secrets() {
  section "Configuring secrets"
  echo "We'll write these to $REPO_DIR/.env (chmod 600). You can edit"
  echo "the file later if anything changes."
  echo

  if [[ -f "$REPO_DIR/.env" ]]; then
    yellow "$REPO_DIR/.env already exists."
    if ! prompt_yesno "Overwrite it?" "n"; then
      green "Keeping existing .env"
      return 0
    fi
  fi

  # Postgres password — generate or paste
  local pg
  if prompt_yesno "Auto-generate POSTGRES_PASSWORD (recommended)?" "y"; then
    pg="$(openssl rand -base64 24 | tr -d '\n=+/')"
    green "POSTGRES_PASSWORD generated"
  else
    prompt_secret pg "POSTGRES_PASSWORD"
    [[ -n "$pg" ]] || { red "POSTGRES_PASSWORD cannot be empty"; exit 1; }
  fi

  # WhatsApp bridge — optional
  local cmb_phone="0" cmb_apikey="disabled" webhook=""
  if prompt_yesno "Enable WhatsApp/CallMeBot alerting?" "n"; then
    prompt_default cmb_phone "  CALLMEBOT_PHONE (e.g. +123456...)" ""
    prompt_secret  cmb_apikey "  CALLMEBOT_APIKEY"
    webhook="http://whatsapp-bridge:9095"
  fi

  # Data dir
  local data_dir
  prompt_default data_dir "Host data directory" "$DATA_DIR_DEFAULT"

  # Image tag — defaults to :latest. The user can update later.
  local tag
  prompt_default tag "Initial CRYPTOLAKE_TAG (matches publish-images.sh)" "latest"

  umask 077
  cat > "$REPO_DIR/.env" <<EOF
# Generated by infra/vps/bootstrap.sh on $(date -u +%FT%TZ)
POSTGRES_PASSWORD=$pg
WEBHOOK_URL=$webhook
CALLMEBOT_PHONE=$cmb_phone
CALLMEBOT_APIKEY=$cmb_apikey
HOST_DATA_DIR=$data_dir
CRYPTOLAKE_TAG=$tag
EOF
  chown "$SUDO_USER:$SUDO_USER" "$REPO_DIR/.env"
  chmod 600 "$REPO_DIR/.env"
  green "Wrote $REPO_DIR/.env (chmod 600, owner $SUDO_USER)"
}

install_docker() {
  section "Installing Docker"
  if command -v docker >/dev/null; then
    green "Docker already installed: $(docker --version)"
    return 0
  fi
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  cat > /etc/apt/sources.list.d/docker.list <<EOF
deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable
EOF
  apt-get update -qq
  apt-get install -y -qq \
    docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
  green "Docker installed: $(docker --version)"
}

add_user_to_docker() {
  if ! id -nG "$SUDO_USER" | tr ' ' '\n' | grep -qx docker; then
    usermod -aG docker "$SUDO_USER"
    yellow "Added $SUDO_USER to 'docker' group — log out and back in to pick it up."
  fi
}

ensure_data_dir() {
  section "Data directory"
  local dir
  dir="$(grep -E '^HOST_DATA_DIR=' "$REPO_DIR/.env" | cut -d= -f2-)"
  dir="${dir:-$DATA_DIR_DEFAULT}"
  mkdir -p "$dir"
  chown "$SUDO_USER:$SUDO_USER" "$dir"
  green "Data dir: $dir (owner $SUDO_USER)"
}

ensure_swap() {
  section "Swap"
  if swapon --show | grep -q /swapfile; then
    green "Swap already active: $(swapon --show --noheadings | head -n1)"
    return 0
  fi
  fallocate -l "$SWAP_SIZE" /swapfile
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q /swapfile /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
  green "Created $SWAP_SIZE swap"
}

ensure_log_rotation() {
  section "Docker daemon log rotation"
  local cfg=/etc/docker/daemon.json
  mkdir -p /etc/docker
  if [[ -f "$cfg" ]] && grep -q max-size "$cfg"; then
    green "Already configured"
    return 0
  fi
  cat > "$cfg" <<'EOF'
{
  "log-driver": "json-file",
  "log-opts": { "max-size": "50m", "max-file": "3" }
}
EOF
  systemctl restart docker
  green "Daemon log rotation: 50m × 3 per container"
}

install_systemd_unit() {
  section "systemd unit"
  sed "s|WorkingDirectory=.*|WorkingDirectory=$REPO_DIR|g" \
    "$REPO_DIR/infra/vps/cryptolake.service" \
    > /etc/systemd/system/cryptolake.service
  systemctl daemon-reload
  systemctl enable cryptolake.service
  green "Enabled cryptolake.service (auto-start on boot)"
}

install_disk_cron() {
  section "Disk-monitor cron"
  local target=/usr/local/bin/cryptolake-disk-monitor
  install -m 0755 "$REPO_DIR/infra/vps/disk-monitor.sh" "$target"
  if ! sudo -u "$SUDO_USER" crontab -l 2>/dev/null | grep -q cryptolake-disk-monitor; then
    (sudo -u "$SUDO_USER" crontab -l 2>/dev/null; echo "0 */6 * * * $target") \
      | sudo -u "$SUDO_USER" crontab -
  fi
  green "Cron: every 6h"
}

main() {
  require_root
  collect_secrets
  install_docker
  add_user_to_docker
  ensure_data_dir
  ensure_swap
  ensure_log_rotation
  install_systemd_unit
  install_disk_cron

  section "Done"
  cat <<EOF
Bootstrap complete on $(hostname).

Next:
  1. (laptop)  scripts/publish-images.sh $SUDO_USER@<this-host>
  2. (here)    sudo systemctl start cryptolake
               # or, equivalently:
               # cd $REPO_DIR && docker compose up -d

If you have not yet run hardening:
  sudo bash $REPO_DIR/infra/vps/harden.sh
EOF
}

main "$@"
