global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: collector
    static_configs:
      - targets: ["collector:8000"]

  - job_name: writer
    static_configs:
      - targets: ["writer:8001"]

  - job_name: backfill
    static_configs:
      - targets: ["backfill:8002"]

  - job_name: redpanda
    static_configs:
      - targets: ["redpanda:9644"]
